#!/bin/bash

VERSION="0.0.5-SNAPSHOT"
INSTALL_DIR=${1:-$(pwd)}

echo "Installing into $INSTALL_DIR"

# check for operating system
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  echo "Assuming on Linux operating system"
  MEM=$(cat /proc/meminfo | grep MemTotal | sed s/^MemTotal:\\\s*\\\|\\\s\\+[^\\\s]*$//g)
  MEM=$(($MEM/2/1024/1024))
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Assuming on MacOS X operating system"
  # sysctl returns total hardware memory size in bytes
  MEM=$(sysctl hw.memsize | grep hw.memsize | sed s/hw.memsize://g)
  MEM=$(($MEM/2/1024/1024/1024))
else
  echo "ERROR - Operating system (arg2) must be either linux or osx - EXITING"
  exit
fi

# mvn clean install
# temporary workaround for openjdk plus surefire bug
_JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn clean install
mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath

echo '#!/bin/bash' > n5-view
echo '' >> n5-view
echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-view
echo 'java \' >> n5-view
echo "  -Xmx${MEM}g \\" >> n5-view
echo '  -XX:+UseConcMarkSweepGC \' >> n5-view
echo -n '  -cp $JAR:' >> n5-view
echo -n $(cat cp.txt) >> n5-view
echo ' \' >> n5-view
echo '  org.janelia.saalfeldlab.View "$@"' >> n5-view

chmod a+x n5-view

echo '#!/bin/bash' > n5-view-cosem
echo '' >> n5-view-cosem
echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-view-cosem
echo 'java \' >> n5-view-cosem
echo "  -Xmx${MEM}g \\" >> n5-view-cosem
echo '  -XX:+UseConcMarkSweepGC \' >> n5-view-cosem
echo -n '  -cp $JAR:' >> n5-view-cosem
echo -n $(cat cp.txt) >> n5-view-cosem
echo ' \' >> n5-view-cosem
echo '  org.janelia.saalfeldlab.cosem.ViewCosem "$@"' >> n5-view-cosem

chmod a+x n5-view-cosem

echo '#!/bin/bash' > n5-copy
echo '' >> n5-copy
echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-copy
echo 'java \' >> n5-copy
echo "  -Xmx${MEM}g \\" >> n5-copy
echo -n '  -cp $JAR:' >> n5-copy
echo -n $(cat cp.txt) >> n5-copy
echo ' \' >> n5-copy
echo '  org.janelia.saalfeldlab.Copy "$@"' >> n5-copy

chmod a+x n5-copy

echo '#!/bin/bash' > n5-equals
echo '' >> n5-equals
echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-equals
echo 'java \' >> n5-equals
echo "  -Xmx${MEM}g \\" >> n5-equals
echo -n '  -cp $JAR:' >> n5-equals
echo -n $(cat cp.txt) >> n5-equals
echo ' \' >> n5-equals
echo '  org.janelia.saalfeldlab.Equals "$@"' >> n5-equals

chmod a+x n5-equals
rm cp.txt

mkdir -p $INSTALL_DIR
mv n5-view $INSTALL_DIR/
mv n5-copy $INSTALL_DIR/
mv n5-equals $INSTALL_DIR/

